#!/usr/bin/env python3
"""Build the submission zip.

    python docs/submission/build.py

Assembles everything the lecturer needs to read the reports and run the app,
under descriptive names, and deliberately leaves out the agent/tooling
scaffolding and the private defence notes. The zip is written to the repository
root and is a build artifact (gitignored) -- rebuild it rather than editing it.

The build fails loudly if a source file is missing, or if anything on the
forbidden list reaches the archive. It writes to a temporary file first, so a
failed run never overwrites a good zip.
"""

from __future__ import annotations

import fnmatch
import os
import subprocess
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent

ZIP_NAME = "Smart-Health-SWE3090XA-Amy-Njau-669008-Submission.zip"
TOP = "Smart Health - SWE3090XA - Amy Njau 669008"

REPORTS = "1 - Reports"
CODE = "2 - Source Code"
FIGURES = "3 - Diagrams"

# The defence deck is NOT shipped. Its speaker-notes panel (the S key) carries
# the presenting script and a "maximum-marks cue" written to the student on
# every slide, and its last slide is an anticipated-questions rehearsal sheet
# whose own note says it is "for you, not the panel". That is private defence
# material of exactly the kind the submission must not contain, and it lives
# inside a file the archive would otherwise ship, where a filename exclusion
# cannot see it. If a notes-free build of the deck is ever produced, add it
# here -- and keep the PRIVATE_PHRASES check below pointing at it.

# --- individual files: (source relative to repo root, path inside the zip) ---
FILES: list[tuple[str, str]] = [
    ("docs/submission/submission-readme.md", "README.md"),
    ("LICENSE", "LICENCE.txt"),

    # Reports -- the -alt-diagrams builds throughout, so every document uses the
    # same (redrawn) figure set.
    ("docs/reports/build/end-semester-report-alt-diagrams.pdf",
     f"{REPORTS}/End of Semester Project Report.pdf"),
    ("docs/reports/build/system-integration-report-alt-diagrams.pdf",
     f"{REPORTS}/System Integration Report.pdf"),
    ("docs/reports/build/project-logbook-alt-diagrams.pdf",
     f"{REPORTS}/Student Project Log-Book.pdf"),
    ("Amy Wanjugu NJau Mid Term Report 2026 Summer  (1).pdf",
     f"{REPORTS}/Mid-Term Report.pdf"),

    ("docs/reports/build/end-semester-report-alt-diagrams.docx",
     f"{REPORTS}/Editable Word Versions/End of Semester Project Report.docx"),
    ("docs/reports/build/system-integration-report-alt-diagrams.docx",
     f"{REPORTS}/Editable Word Versions/System Integration Report.docx"),
    ("docs/reports/build/project-logbook-alt-diagrams.docx",
     f"{REPORTS}/Editable Word Versions/Student Project Log-Book.docx"),

    ("AMY WANJUGU NJAU PROJECT CONCEPT (1).docx",
     f"{REPORTS}/Earlier Coursework Submissions/Project Concept.docx"),
    ("Amy Njau SWE3090XA UI DB Code Design Report (1).docx",
     f"{REPORTS}/Earlier Coursework Submissions/UI, Database and Code Design Report.docx"),
    ("SWE3090XA Screenshots UML DESIGNS (1).docx",
     f"{REPORTS}/Earlier Coursework Submissions/Screenshots and UML Designs.docx"),

    # Source code
    ("docs/submission/how-to-run-the-app.md", f"{CODE}/How to Run the App.md"),

    # Diagrams -- the same redrawn set the reports use. SVG opens in any browser.
    ("docs/figures/alt/fig3_1_architecture.svg",
     f"{FIGURES}/Figure 3.1 - Integration Architecture.svg"),
    ("docs/figures/alt/fig3_2_sequence.svg",
     f"{FIGURES}/Figure 3.2 - End-to-End Data Flow (Sequence).svg"),
    ("docs/figures/alt/fig4_1_architecture_delivered.svg",
     f"{FIGURES}/Figure 4.1 - Three-Tier Architecture of the Delivered System.svg"),
    ("docs/figures/alt/figA_1_erd.svg",
     f"{FIGURES}/Figure A.1 - Entity Relationship Diagram.svg"),
]

# --- whole directories: (source, destination, extra excludes) ---
DIRECTORIES: list[tuple[str, str, tuple[str, ...]]] = [
    ("backend", f"{CODE}/backend", (".env", "*.log", ".gitignore")),
    # .flutter-plugins-dependencies is regenerated by `flutter pub get` and
    # holds absolute paths from this machine's pub cache -- never ship it.
    # mobile/.run/ IS shipped: it gives Android Studio a ready Run configuration
    # with the API address already passed to --dart-define.
    # .gitignore files are dropped: the marker has no repository, and the
    # Android one would claim that files sitting right beside it are ignored.
    # GeneratedPluginRegistrant.java is regenerated by `flutter pub get`.
    ("mobile", f"{CODE}/mobile", (
        "*.iml", ".metadata", "local.properties", ".gitignore",
        ".flutter-plugins", ".flutter-plugins-dependencies",
        "GeneratedPluginRegistrant.java", "*(profile*",
    )),
]

# Never copied, from anywhere.
EXCLUDED_NAMES = {
    ".git", ".github", ".claude", ".gstack", ".idea", ".vscode",
    "node_modules", "__pycache__", ".dart_tool", "build", ".gradle",
    ".kotlin", "Thumbs.db", ".DS_Store", "desktop.ini",
}
EXCLUDED_SUFFIXES = (".pyc",)

# The backend needs the Firebase project id to verify the ID tokens the app
# sends; without it every signed-in request fails. .env is gitignored, so the
# submitted copy gets one written here. Nothing in it is secret.
BACKEND_ENV = """\
# Configuration for the submitted copy. See backend/.env.example for the rest.
PORT=3000

# Data layer: "local" (JSON files, no setup) or "firestore".
DATA_STORE=local

# Nearby providers: "mock" (sample data, no key needed) or "google".
PROVIDER_SOURCE=mock

# Firebase project whose sign-in tokens the API accepts. Required as soon as
# the app signs in: without it the API cannot verify a token at all.
FIREBASE_PROJECT_ID=smart-health-swe3090xa

# Set to true to reject anonymous requests to /api/diagnose and /api/providers.
# A token that IS supplied is verified either way.
AUTH_REQUIRED=false
"""

# Private material identifiable only by what is inside a file, not by its name.
# The presenter script and the rubric coaching live inside the deck's HTML.
PRIVATE_PHRASES = (
    "Maximum-marks cue",
    "Presenter script",
    "for you, not the panel",
)

# If any of these turns up in the finished archive, the build is wrong.
FORBIDDEN = [
    "*/CLAUDE.md", "*/PROJECT.md", "*/LAUNCH.md",
    "*internal-notes*", "*PRIVATE-*", "*Nipo_IST4078A*",
    "*/.git/*", "*/.claude/*", "*/.gstack/*", "*/.idea/*", "*.iml",
    "*/node_modules/*", "*__pycache__*", "*.pyc",
    "*/.dart_tool/*", "*/.gradle/*", "*/.kotlin/*", "*local.properties",
    "*/build/*", "*.flutter-plugins*",
]

# Every one of these must exist in the archive, or something was dropped.
REQUIRED = [
    "README.md",
    "LICENCE.txt",
    f"{REPORTS}/End of Semester Project Report.pdf",
    f"{REPORTS}/System Integration Report.pdf",
    f"{REPORTS}/Student Project Log-Book.pdf",
    f"{REPORTS}/Mid-Term Report.pdf",
    f"{CODE}/How to Run the App.md",
    f"{CODE}/backend/package.json",
    f"{CODE}/backend/src/services/diagnosisEngine.js",
    f"{CODE}/backend/src/data/knowledge_base.json",
    f"{CODE}/backend/tests/api.test.js",
    f"{CODE}/backend/.env",
    f"{CODE}/backend/.env.example",
    f"{CODE}/mobile/pubspec.yaml",
    f"{CODE}/mobile/lib/main.dart",
    f"{CODE}/mobile/android/app/src/main/AndroidManifest.xml",
    f"{CODE}/mobile/android/app/google-services.json",
    f"{CODE}/mobile/android/gradlew",
    f"{CODE}/mobile/android/gradle/wrapper/gradle-wrapper.jar",
    f"{CODE}/mobile/.run/main.dart.run.xml",
    f"{FIGURES}/Figure A.1 - Entity Relationship Diagram.svg",
]


def fail(message: str) -> None:
    sys.exit(f"submission build FAILED: {message}")


def is_excluded(name: str, extra: tuple[str, ...]) -> bool:
    if name in EXCLUDED_NAMES or name.endswith(EXCLUDED_SUFFIXES):
        return True
    return any(fnmatch.fnmatch(name, pattern) for pattern in extra)


def tracked_files() -> set[Path]:
    """Every path git tracks, absolute. Used to keep the zip reproducible."""
    proc = subprocess.run(
        ["git", "-C", str(ROOT), "ls-files", "-z"],
        capture_output=True, text=True, encoding="utf-8",
    )
    if proc.returncode != 0:
        fail("could not list tracked files: " + (proc.stderr or "").strip())
    return {ROOT / name for name in proc.stdout.split(chr(0)) if name}


def collect(entries: list[tuple[Path, str]]) -> None:
    """Resolve the declared sources into (absolute path, archive name) pairs."""
    for source, target in FILES:
        path = ROOT / source
        if not path.is_file():
            fail(f"missing source file: {source}")
        entries.append((path, f"{TOP}/{target}"))

    for source, target, extra in DIRECTORIES:
        base = ROOT / source
        if not base.is_dir():
            fail(f"missing source directory: {source}")
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = sorted(d for d in dirnames if not is_excluded(d, extra))
            for filename in sorted(filenames):
                if is_excluded(filename, extra):
                    continue
                path = Path(dirpath) / filename
                relative = path.relative_to(base).as_posix()
                entries.append((path, f"{TOP}/{target}/{relative}"))


def verify(zip_path: Path) -> list[str]:
    with zipfile.ZipFile(zip_path) as archive:
        names = archive.namelist()
        bad = [n for n in names if archive.getinfo(n).file_size == 0]
        if bad:
            fail("empty files in the archive: " + ", ".join(bad[:5]))

        # Private material hides inside files, not only in their names: the
        # deck's speaker notes are the case this exists for.
        for name in names:
            if not name.lower().endswith((".html", ".htm", ".md", ".txt")):
                continue
            text = archive.read(name).decode("utf-8", "replace")
            for phrase in PRIVATE_PHRASES:
                if phrase in text:
                    fail(f"{name} contains private presenter material: {phrase!r}")

    for pattern in FORBIDDEN:
        hits = [n for n in names if fnmatch.fnmatch(n, pattern)]
        if hits:
            fail(f"forbidden content matched {pattern}: {hits[:3]}")

    for required in REQUIRED:
        if f"{TOP}/{required}" not in names:
            fail(f"expected file is not in the archive: {required}")

    return names


def main() -> None:
    entries: list[tuple[Path, str]] = []
    collect(entries)

    env_arcname = f"{TOP}/{CODE}/backend/.env"
    seen: dict[str, Path] = {env_arcname: Path("<generated .env>")}
    for path, arcname in entries:
        if arcname in seen:
            fail(f"two sources map to {arcname}: {seen[arcname]} and {path}")
        seen[arcname] = path

    # Everything shipped out of backend/ and mobile/ must be a tracked file, or
    # the zip depends on whatever happens to be lying in this working tree and
    # cannot be rebuilt from a clone. Only the generated .env is exempt.
    tracked = tracked_files()
    untracked = sorted(
        str(path.relative_to(ROOT))
        for path, arcname in entries
        if f"/{CODE}/" in arcname and path not in tracked
    )
    if untracked:
        fail(
            "these files would ship but are not tracked by git, so the zip is "
            "not reproducible from the repository: " + ", ".join(untracked[:10])
        )

    final = ROOT / ZIP_NAME
    temporary = ROOT / (ZIP_NAME + ".tmp")

    try:
        with zipfile.ZipFile(temporary, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
            for path, arcname in entries:
                archive.write(path, arcname)
            archive.writestr(env_arcname, BACKEND_ENV)

        names = verify(temporary)

        # One call, so a lock between deleting and renaming cannot leave the
        # repository with neither zip.
        temporary.replace(final)
    finally:
        temporary.unlink(missing_ok=True)

    size = final.stat().st_size
    print(f"{final.name}  ({size / 1_048_576:.1f} MB, {len(names)} files)\n")

    top_level: dict[str, int] = {}
    for name in names:
        parts = name.split("/")
        key = parts[1] if len(parts) > 2 else parts[-1]
        top_level[key] = top_level.get(key, 0) + 1
    for key in sorted(top_level):
        count = top_level[key]
        print(f"  {key}{'' if count == 1 else f'  ({count} files)'}")


if __name__ == "__main__":
    main()
